In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/공모전/광진구/서울특별시 광진구_옐로우카펫 설치 현황_20230102.csv',encoding ='euc-kr' )
df

,연번,설치학교명,도로명 주소,설치년도,수량,관리기관,전화번호,데이터기준일자
0,1,구남초등학교,서울특별시 광진구 구의강변로 69,2016,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
1,2,광진초등학교,서울특별시 광진구 자양로40길 41,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
2,3,광장초등학교,서울특별시 광진구 광장로 45,2016,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
3,4,광장초등학교,서울특별시 광진구 광장로1길 1,2016,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
4,5,광장초등학교,서울특별시 광진구 광장로3길 2,2016,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
5,6,광장초등학교,서울특별시 광진구 광장로 56,2016,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
6,7,성자초등학교,서울특별시 광진구 뚝섬로56길 7,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
7,8,양남초등학교,서울특별시 광진구 뚝섬로64길 71,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
8,9,신양초등학교,서울특별시 광진구 능동로 42,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
9,10,동자초등학교,서울특별시 광진구 뚝섬로 561,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
10,11,세종초등학교,서울특별시 광진구 군자로 114,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
11,12,장안초등학교,서울특별시 광진구 군자로 74,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
12,13,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
13,14,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
14,15,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
15,16,동의초등학교,서울특별시 광진구 영화사로 111,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
16,17,동의초등학교,서울특별시 광진구 영화사로 105,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
17,18,동의초등학교,서울특별시 광진구 영화사로16길 43,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
18,19,동의초등학교,서울특별시 광진구 영화사로16길 43,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
19,20,동의초등학교,서울특별시 광진구 구의동 6,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
20,21,동의초등학교,서울특별시 광진구 구의동 5-2,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
21,22,양진초등학교,서울특별시 광진구 워커힐로 32,2018,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
22,23,경복초등학교,서울특별시 광진구 천호대로130길 58,2018,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
23,24,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
24,25,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
25,26,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
26,27,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
27,28,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
28,29,구남초등학교,서울특별시 광진구 구의강변로 69,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
29,30,자양초등학교,서울특별시 광진구 아차산로44길 26,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
30,31,광남초등학교,서울특별시 광진구 아차산로70길 35,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
31,32,광남초등학교,서울특별시 광진구 아차산로70길 35,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
32,33,신자초등학교,서울특별시 광진구 뚝섬로46길 64,2019,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
33,34,양진초등학교,서울특별시 광진구 워커힐로 32,2020,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
34,35,양진초등학교,서울특별시 광진구 워커힐로 32,2020,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02
35,36,성동초등학교,서울특별시 광진구 뚝섬로66길 4,2017,1,서울특별시 광진구청 교통행정과,02-450-7928,2023-01-02

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   연번       36 non-null     int64
 1   설치학교명    36 non-null     object
 2   도로명 주소   36 non-null     object
 3   설치년도     36 non-null     int64
 4   수량       36 non-null     int64
 5   관리기관     36 non-null     object
 6   전화번호     36 non-null     object
 7   데이터기준일자  36 non-null     object
dtypes: int64(3), object(5)
memory usage: 2.4+ KB

In [ ]:
#결측치 확인
df.isnull().sum()

연번         0
설치학교명      0
도로명 주소     0
설치년도       0
수량         0
관리기관       0
전화번호       0
데이터기준일자    0
dtype: int64

In [ ]:
#컬럼 제거
df.drop(['연번','설치년도','관리기관','전화번호','데이터기준일자'],inplace=True,axis=1)
df

     설치학교명                 도로명 주소  수량
0   구남초등학교     서울특별시 광진구 구의강변로 69   1
1   광진초등학교    서울특별시 광진구 자양로40길 41   1
2   광장초등학교       서울특별시 광진구 광장로 45   1
3   광장초등학교      서울특별시 광진구 광장로1길 1   1
4   광장초등학교      서울특별시 광진구 광장로3길 2   1
5   광장초등학교       서울특별시 광진구 광장로 56   1
6   성자초등학교     서울특별시 광진구 뚝섬로56길 7   1
7   양남초등학교    서울특별시 광진구 뚝섬로64길 71   1
8   신양초등학교       서울특별시 광진구 능동로 42   1
9   동자초등학교      서울특별시 광진구 뚝섬로 561   1
10  세종초등학교      서울특별시 광진구 군자로 114   1
11  장안초등학교       서울특별시 광진구 군자로 74   1
12  구남초등학교     서울특별시 광진구 구의강변로 69   1
13  구남초등학교     서울특별시 광진구 구의강변로 69   1
14  구남초등학교     서울특별시 광진구 구의강변로 69   1
15  동의초등학교     서울특별시 광진구 영화사로 111   1
16  동의초등학교     서울특별시 광진구 영화사로 105   1
17  동의초등학교   서울특별시 광진구 영화사로16길 43   1
18  동의초등학교   서울특별시 광진구 영화사로16길 43   1
19  동의초등학교        서울특별시 광진구 구의동 6   1
20  동의초등학교      서울특별시 광진구 구의동 5-2   1
21  양진초등학교      서울특별시 광진구 워커힐로 32   1
22  경복초등학교  서울특별시 광진구 천호대로130길 58   1
23  구남초등학교     서울특별시 광진구 구의강변로 69   1
24  구남초등학교     서울특별시 광진구 구의강변로 69   1
25  구남초등학교     서울특별시 광진구 구의강변로 69   1
26  구남초등학교     서울특별시 광진구 구의강변로 69   1
27  구남초등학교     서울특별시 광진구 구의강변로 69   1
28  구남초등학교     서울특별시 광진구 구의강변로 69   1
29  자양초등학교   서울특별시 광진구 아차산로44길 26   1
30  광남초등학교   서울특별시 광진구 아차산로70길 35   1
31  광남초등학교   서울특별시 광진구 아차산로70길 35   1
32  신자초등학교    서울특별시 광진구 뚝섬로46길 64   1
33  양진초등학교      서울특별시 광진구 워커힐로 32   1
34  양진초등학교      서울특별시 광진구 워커힐로 32   1
35  성동초등학교     서울특별시 광진구 뚝섬로66길 4   1

In [ ]:
#데이터프레임 주소값 추출
address = df['도로명 주소']
address

0        서울특별시 광진구 구의강변로 69
1       서울특별시 광진구 자양로40길 41
2          서울특별시 광진구 광장로 45
3         서울특별시 광진구 광장로1길 1
4         서울특별시 광진구 광장로3길 2
5          서울특별시 광진구 광장로 56
6        서울특별시 광진구 뚝섬로56길 7
7       서울특별시 광진구 뚝섬로64길 71
8          서울특별시 광진구 능동로 42
9         서울특별시 광진구 뚝섬로 561
10        서울특별시 광진구 군자로 114
11         서울특별시 광진구 군자로 74
12       서울특별시 광진구 구의강변로 69
13       서울특별시 광진구 구의강변로 69
14       서울특별시 광진구 구의강변로 69
15       서울특별시 광진구 영화사로 111
16       서울특별시 광진구 영화사로 105
17     서울특별시 광진구 영화사로16길 43
18     서울특별시 광진구 영화사로16길 43
19          서울특별시 광진구 구의동 6
20        서울특별시 광진구 구의동 5-2
21        서울특별시 광진구 워커힐로 32
22    서울특별시 광진구 천호대로130길 58
23       서울특별시 광진구 구의강변로 69
24       서울특별시 광진구 구의강변로 69
25       서울특별시 광진구 구의강변로 69
26       서울특별시 광진구 구의강변로 69
27       서울특별시 광진구 구의강변로 69
28       서울특별시 광진구 구의강변로 69
29     서울특별시 광진구 아차산로44길 26
30     서울특별시 광진구 아차산로70길 35
31     서울특별시 광진구 아차산로70길 35
32      서울특별시 광진구 뚝섬로46길 64
33        서울특별시 광진구 워커힐로 32
34        서울특별시 광진구 워커힐로 32
35       서울특별시 광진구 뚝섬로66길 4
Name: 도로명 주소, dtype: object

In [ ]:
####### 도로명주소 위도 경도 값으로 바꿔주기 ########
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

# 위도, 경도 반환하는 함수
def geocoding(address):
    try:
        geo = geo_local.geocode(address)
        x_y = [geo.latitude, geo.longitude]
        return x_y

    except:
        return [0,0]

#####주소를 위,경도 값으로 변환하기 #####
latitude = []
longitude =[]

for i in address:
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

In [ ]:
#####Dataframe만들기######
address_df = pd.DataFrame({'설치학교': df['설치학교명'],'도로명 주소':df['도로명 주소'],'위도':latitude,'경도':longitude})

#df저장
address_df.to_csv('Gwangjingu_yellowcarpet.csv')

In [ ]:
address_df

      설치학교                 도로명 주소         위도          경도
0   구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
1   광진초등학교    서울특별시 광진구 자양로40길 41  37.547771  127.090282
2   광장초등학교       서울특별시 광진구 광장로 45  37.547349  127.104197
3   광장초등학교      서울특별시 광진구 광장로1길 1  37.547471  127.103055
4   광장초등학교      서울특별시 광진구 광장로3길 2  37.547664  127.102790
5   광장초등학교       서울특별시 광진구 광장로 56  37.547349  127.104197
6   성자초등학교     서울특별시 광진구 뚝섬로56길 7  37.529804  127.082166
7   양남초등학교    서울특별시 광진구 뚝섬로64길 71  37.533044  127.088830
8   신양초등학교       서울특별시 광진구 능동로 42  37.534031  127.067805
9   동자초등학교      서울특별시 광진구 뚝섬로 561  37.533470  127.088300
10  세종초등학교      서울특별시 광진구 군자로 114  37.543340  127.071636
11  장안초등학교       서울특별시 광진구 군자로 74  37.543340  127.071636
12  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
13  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
14  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
15  동의초등학교     서울특별시 광진구 영화사로 111  37.552512  127.099599
16  동의초등학교     서울특별시 광진구 영화사로 105  37.552512  127.099599
17  동의초등학교   서울특별시 광진구 영화사로16길 43  37.554063  127.095146
18  동의초등학교   서울특별시 광진구 영화사로16길 43  37.554063  127.095146
19  동의초등학교        서울특별시 광진구 구의동 6  37.544170  127.092620
20  동의초등학교      서울특별시 광진구 구의동 5-2  37.544170  127.092620
21  양진초등학교      서울특별시 광진구 워커힐로 32  37.543260  127.095330
22  경복초등학교  서울특별시 광진구 천호대로130길 58  37.549526  127.087839
23  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
24  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
25  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
26  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
27  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
28  구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
29  자양초등학교   서울특별시 광진구 아차산로44길 26  37.536457  127.079692
30  광남초등학교   서울특별시 광진구 아차산로70길 35  37.539280  127.098383
31  광남초등학교   서울특별시 광진구 아차산로70길 35  37.539280  127.098383
32  신자초등학교    서울특별시 광진구 뚝섬로46길 64  37.529686  127.076476
33  양진초등학교      서울특별시 광진구 워커힐로 32  37.543260  127.095330
34  양진초등학교      서울특별시 광진구 워커힐로 32  37.543260  127.095330
35  성동초등학교     서울특별시 광진구 뚝섬로66길 4  37.532466  127.090228

In [ ]:
address_df['설치학교'].value_counts()

구남초등학교    10
동의초등학교     6
광장초등학교     4
양진초등학교     3
광남초등학교     2
광진초등학교     1
성자초등학교     1
양남초등학교     1
신양초등학교     1
동자초등학교     1
세종초등학교     1
장안초등학교     1
경복초등학교     1
자양초등학교     1
신자초등학교     1
성동초등학교     1
Name: 설치학교, dtype: int64

In [ ]:
#위도경도 같은 값인 중복 데이터 제거
address_df.drop_duplicates(['위도'])
address_df.drop_duplicates(['경도'])

      설치학교                 도로명 주소         위도          경도
0   구남초등학교     서울특별시 광진구 구의강변로 69  37.535520  127.092110
1   광진초등학교    서울특별시 광진구 자양로40길 41  37.547771  127.090282
2   광장초등학교       서울특별시 광진구 광장로 45  37.547349  127.104197
3   광장초등학교      서울특별시 광진구 광장로1길 1  37.547471  127.103055
4   광장초등학교      서울특별시 광진구 광장로3길 2  37.547664  127.102790
6   성자초등학교     서울특별시 광진구 뚝섬로56길 7  37.529804  127.082166
7   양남초등학교    서울특별시 광진구 뚝섬로64길 71  37.533044  127.088830
8   신양초등학교       서울특별시 광진구 능동로 42  37.534031  127.067805
9   동자초등학교      서울특별시 광진구 뚝섬로 561  37.533470  127.088300
10  세종초등학교      서울특별시 광진구 군자로 114  37.543340  127.071636
15  동의초등학교     서울특별시 광진구 영화사로 111  37.552512  127.099599
17  동의초등학교   서울특별시 광진구 영화사로16길 43  37.554063  127.095146
19  동의초등학교        서울특별시 광진구 구의동 6  37.544170  127.092620
21  양진초등학교      서울특별시 광진구 워커힐로 32  37.543260  127.095330
22  경복초등학교  서울특별시 광진구 천호대로130길 58  37.549526  127.087839
29  자양초등학교   서울특별시 광진구 아차산로44길 26  37.536457  127.079692
30  광남초등학교   서울특별시 광진구 아차산로70길 35  37.539280  127.098383
32  신자초등학교    서울특별시 광진구 뚝섬로46길 64  37.529686  127.076476
35  성동초등학교     서울특별시 광진구 뚝섬로66길 4  37.532466  127.090228