In [2]:
import pandas as pd
import numpy as np

In [298]:
academy = pd.read_csv("../기존 입지 분석 이용 데이터/서울시 어린이보호구역 학원가 지정.csv", encoding = 'cp949')
academy

    지역구               도로명주소             시설명
0   노원구   서울시 노원구 한글비석로 232  중계미래탐구초등연재센터학원
1   노원구   서울시 노원구 한글비석로 272         중계덕스어학원
2   노원구   서울시 노원구 한글비석로 250      아발론랭콘중계어학원
3   노원구     서울시 노원구 중계로 198      하이레벨수학전문학원
4   노원구   서울시 노원구 한글비석로 232       소마사고력수학학원
5   노원구     서울시 노원구 중계로 218           청담어학원
6   노원구   서울시 노원구 한글비석로 232        중계스텔라어학원
7   노원구     서울시 노원구 중계로 202        국풍2000학원
8   노원구   서울시 노원구 한글비석로 270     올림피아드영재센터학원
9   노원구   서울시 노원구 한글비석로 231       모멘텀아스트라학원
10  노원구     서울시 노원구 중계로 218       알로곤영재센터학원
11  노원구     서울시 노원구 중계로 198      하이레벨수학전문학원
12  노원구     서울시 노원구 중계로 206           멘처스학원
13  노원구     서울시 노원구 중계로 206        중계세일입시학원
14  노원구     서울시 노원구 중계로 225   CMS중계중등영재2관학원
15  노원구     서울시 노원구 중계로 219   수학에미친사람들중계관학원
16  강남구     서울시 강남구 삼성로 341          강남최강학원
17  강남구    서울시 강남구 도곡로73길 5            새움학원
18  강남구     서울시 강남구 도곡로 505        시대인재15학원
19  강남구     서울시 강남구 도곡로 510        시대인재2관학원
20  강남구     서울시 강남구 도곡로 434        시대인재98학원
21  강남구     서울시 강남구 도곡로 428        시대인재99학원
22  강남구     서울시 강남구 도곡로 460          시대인재학원
23  강남구     서울시 강남구 삼성로 212         신어지은마학원
24  강남구     서울시 강남구 도곡로 323         씨앤씨미술학원
25  강남구     서울시 강남구 도곡로 323       프라임스템경원학원
26  강남구     서울시 강남구 도곡로 423          한티매쓰학원
27  강남구     서울시 강남구 삼성로 314          소마대치본원
28  강남구     서울시 강남구 도곡로 450          씨엔에이논술
29  강남구     서울시 강남구 도곡로 434          미래탐구학원
30  강남구  서울시 강남구 남부순환로 2935            짱솔학원
31  강남구     서울시 강남구 삼성로 155         파르테논어학원

In [299]:
# 어린이 보호 구역으로 선정된 강남구의 학원 목록
a1 = list(academy[academy['지역구'] == '강남구'].iloc[:,2])
a1

['강남최강학원',
 '새움학원',
 '시대인재15학원',
 '시대인재2관학원',
 '시대인재98학원',
 '시대인재99학원',
 '시대인재학원',
 '신어지은마학원',
 '씨앤씨미술학원',
 '프라임스템경원학원',
 '한티매쓰학원',
 '소마대치본원',
 '씨엔에이논술',
 '미래탐구학원',
 '짱솔학원',
 '파르테논어학원']

In [300]:
# 강남구 전체 학원 인원과 좌표
gn_all = pd.read_csv("../기존 입지 분석 이용 데이터/강남구 학원 좌표화&인원.csv")
gn_all

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0
...,...,...,...,...,...,...
3663,김형은수학교습소,서울특별시 강남구 선릉로 227,37.495832,127.052729,4,20.0
3664,대치지아이(Daechi GI)영어교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,40,8.0
3665,소리샘피아노교습소,서울특별시 강남구 광평로10길 15,37.482024,127.082132,9,3.0
3666,예섬프론티어학원,서울특별시 강남구 도곡로 430,37.497506,127.057551,2840,278.0
3667,대찬학원,서울특별시 강남구 도곡로 432,37.497571,127.057751,28565,130.0

In [177]:
# gn_all.drop('어린이보호구역지정여부', axis = 'columns', inplace=True)

In [301]:
# 해당 학원 어린이보호구역 지정 여부
gn_all.loc[gn_all['학원명'].isin(a1),'어린이보호구역여부'] = 1
gn_all

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0,NaN
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0,NaN
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0,NaN
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0,NaN
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0,NaN
...,...,...,...,...,...,...,...
3663,김형은수학교습소,서울특별시 강남구 선릉로 227,37.495832,127.052729,4,20.0,NaN
3664,대치지아이(Daechi GI)영어교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,40,8.0,NaN
3665,소리샘피아노교습소,서울특별시 강남구 광평로10길 15,37.482024,127.082132,9,3.0,NaN
3666,예섬프론티어학원,서울특별시 강남구 도곡로 430,37.497506,127.057551,2840,278.0,NaN
3667,대찬학원,서울특별시 강남구 도곡로 432,37.497571,127.057751,28565,130.0,NaN

In [302]:
a2 = list(gn_all[gn_all['학원명'].isin(academy['시설명'])].iloc[:,0])
a2

['미래탐구학원',
 '파르테논어학원',
 '강남최강학원',
 '짱솔학원',
 '새움학원',
 '올림피아드영재센터학원',
 '시대인재99학원',
 '시대인재98학원',
 '시대인재15학원',
 '시대인재2관학원']

In [303]:
# 전체 리스트에서 누락 학원 찾기
gn_missing = list(set(a1)-set(a2))
gn_missing

['소마대치본원', '프라임스템경원학원', '시대인재학원', '씨엔에이논술', '신어지은마학원', '한티매쓰학원', '씨앤씨미술학원']

In [304]:
# 학원 브랜치가 분리된 듯
gn_all[gn_all['학원명'].str.find('소마')>=0]

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
224,대치소마학원,서울특별시 강남구 삼성로 314,37.500035,127.060650,64,88.0,NaN
621,압구정소마학원,서울특별시 강남구 언주로 844,37.525644,127.033868,56,76.0,NaN
1262,대치소마2관학원,서울특별시 강남구 도곡로 515,37.499835,127.062650,40,68.0,NaN
1306,세곡소마수학학원,서울특별시 강남구 헌릉로,37.465916,127.112251,10,70.0,NaN
3057,프리미어소마학원,서울특별시 강남구 삼성로 314,37.500035,127.060650,50,75.0,NaN

In [305]:
#프라임스템경원학원 -> 프라임스템주니어학원
gn_all.loc[gn_all['학원명'].str.find('프라임스템')>=0, '어린이보호구역여부']=1

In [306]:
gn_all[gn_all['학원명'].str.find('프라임스템')>=0]

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
1766,프라임스템주니어학원,서울특별시 강남구 역삼로 448,37.501999,127.056229,1101,459.0,1.0

In [307]:
gn_all[gn_all['학원명'].str.find('시대인재')>=0] # 시대인재의 경우 엄청 나눠져있다..

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
106,시대인재56학원,서울특별시 강남구 삼성로 231,37.497828,127.061014,10530,104.0,NaN
144,시대인재87학원,서울특별시 강남구 삼성로57길 22,37.497840,127.059257,10530,74.0,NaN
525,시대인재A관3층학원,서울특별시 강남구 삼성로 324,37.500848,127.060130,10530,160.0,NaN
840,시대인재H관학원,서울특별시 강남구 도곡로 453,37.498939,127.059921,10530,208.0,NaN
1183,시대인재11학원,서울특별시 강남구 삼성로 324,37.500848,127.060130,10530,156.0,NaN
1208,시대인재3관학원,서울특별시 강남구 도곡로 510,37.498912,127.061955,10530,124.0,NaN
1431,시대인재7관학원,서울특별시 강남구 도곡로 516,37.499203,127.063100,10530,168.0,NaN
1632,시대인재99학원,서울특별시 강남구 도곡로 428,37.497442,127.057351,10530,132.0,1.0
1643,시대인재77학원,서울특별시 강남구 도곡로 460,37.498394,127.060645,11610,236.0,NaN
1649,시대인재88학원,서울특별시 강남구 삼성로57길 22,37.497840,127.059257,10530,82.0,NaN
1703,시대인재서바이벌관학원,서울특별시 강남구 도곡로 510,37.498912,127.061955,10530,104.0,NaN
1746,시대인재부엉이라이브러리이(E)관5독서실,서울특별시 강남구 도곡로 503,37.499387,127.061403,143,86.0,NaN
1750,시대인재부엉이라이브러리이(E)관6독서실,서울특별시 강남구 도곡로 503,37.499387,127.061403,143,86.0,NaN
1759,시대인재98학원,서울특별시 강남구 도곡로 434,37.497636,127.057955,10530,155.0,1.0
1841,시대인재부엉이라이브러리신관학원,서울특별시 강남구 삼성로51길 11,37.496256,127.060622,11610,730.0,NaN
1850,시대인재부엉이라이브러리신관독서실,서울특별시 강남구 삼성로51길 11,37.496256,127.060622,57,282.0,NaN
1862,시대인재15학원,서울특별시 강남구 도곡로 451,37.498884,127.059753,10530,194.0,1.0
1883,시대인재온원격학원,서울특별시 강남구 도곡로78길 6,37.497748,127.058921,8000,1000.0,NaN
1968,시대인재수학관학원,서울특별시 강남구 삼성로58길 9,37.498729,127.062010,10530,134.0,NaN
2077,시대인재부엉이라이브러리엔(N)학원,서울특별시 강남구 도곡로 505,37.499563,127.061668,11610,265.0,NaN
2093,시대인재16학원,서울특별시 강남구 도곡로 451,37.498884,127.059753,10530,209.0,NaN
2159,시대인재78학원,서울특별시 강남구 도곡로 460,37.498394,127.060645,11610,192.0,NaN
2166,시대인재대덕관5층학원,서울특별시 강남구 삼성로57길 36,37.497551,127.058383,10530,76.0,NaN
2352,시대인재앤(N)관학원,서울특별시 강남구 도곡로 505,37.499563,127.061668,11610,235.0,NaN
2460,시대인재23학원,서울특별시 강남구 삼성로57길 36,37.497551,127.058383,10530,133.0,NaN
2461,시대인재33학원,서울특별시 강남구 삼성로57길 36,37.497551,127.058383,10530,132.0,NaN
2481,시대인재대덕관1층학원,서울특별시 강남구 삼성로57길 36,37.497551,127.058383,10530,306.0,NaN
2558,시대인재부엉이라이브러리엠(M)관학원,서울특별시 강남구 도곡로 527,37.500312,127.063973,11610,132.0,NaN
2563,시대인재부엉이라이브러리엠(M)관독서실,서울특별시 강남구 도곡로 527,37.500312,127.063973,57,67.0,NaN
2601,시대인재부엉이라이브러리신관4독서실,서울특별시 강남구 삼성로51길 11,37.496256,127.060622,57,300.0,NaN
2616,시대인재부엉이라이브러리엔(N)2학원,서울특별시 강남구 도곡로 505,37.499563,127.061668,11610,267.0,NaN
2618,시대인재부엉이라이브러리엔(N)2독서실,서울특별시 강남구 도곡로 505,37.499563,127.061668,57,312.0,NaN
2619,시대인재부엉이라이브러리엔(N)독서실,서울특별시 강남구 도곡로 505,37.499563,127.061668,57,320.0,NaN
2625,시대인재부엉이라이브러리신관2학원,서울특별시 강남구 삼성로51길 11,37.496256,127.060622,11610,267.0,NaN
2626,시대인재부엉이라이브러리신관2독서실,서울특별시 강남구 삼성로51길 11,37.496256,127.060622,57,46.0,NaN
2637,시대인재부엉이라이브러리엠(M)3관학원,서울특별시 강남구 도곡로 527,37.500312,127.063973,11610,185.0,NaN
2646,시대인재부엉이라이브러리엠(M)2관독서실,서울특별시 강남구 도곡로 527,37.500312,127.063973,151,94.0,NaN
2647,시대인재부엉이라이브러리엠(M)3관독서실,서울특별시 강남구 도곡로 527,37.500312,127.063973,157,100.0,NaN
2648,시대인재부엉이라이브러리엠(M)4관독서실,서울특별시 강남구 도곡로 527,37.500312,127.063973,151,94.0,NaN
2675,시대인재입시알앤디(R&D)센터학원,서울특별시 강남구 삼성로57길 28,37.497686,127.058729,40,77.0,NaN
2851,시대인재부엉이라이브러리이(E)관3학원,서울특별시 강남구 도곡로 503,37.499387,127.061403,11610,120.0,NaN
2854,시대인재부엉이라이브러리지(G)관독서실,서울특별시 강남구 삼성로57길 7,37.497970,127.060476,189,132.0,NaN
2859,시대인재부엉이라이브러리이(E)관4독서실,서울특별시 강남구 도곡로 503,37.499387,127.061403,117,60.0,NaN
2890,시대인재대덕관4층학원,서울특별시 강남구 삼성로57길 36,37.497551,127.058383,10530,133.0,NaN
3043,시대인재본관6층학원,서울특별시 강남구 도곡로 460,37.498394,127.060645,11610,225.0,NaN
3170,시대인재부엉이라이브러리더블유(W)관6층학원,서울특별시 강남구 삼성로 337,37.502124,127.059690,11610,192.0,NaN
3171,시대인재부엉이라이브러리더블유(W)관7층학원,서울특별시 강남구 삼성로 337,37.502124,127.059690,11610,192.0,NaN
3172,시대인재부엉이라이브러리더블유(W)관8층학원,서울특별시 강남구 삼성로 337,37.502124,127.059690,11610,218.0,NaN
3173,시대인재부엉이라이브러리더블유(W)관9층독서실,서울특별시 강남구 삼성로 337,37.502124,127.059690,292,146.0,NaN
3174,시대인재부엉이라이브러리더블유(W)관10층독서실,서울특별시 강남구 삼성로 337,37.502124,127.059690,308,154.0,NaN
3175,시대인재부엉이라이브러리더블유(W)관학원,서울특별시 강남구 삼성로 337,37.502124,127.059690,11610,124.0,NaN
3176,시대인재부엉이라이브러리더블유(W)관3층독서실,서울특별시 강남구 삼성로 337,37.502124,127.059690,292,146.0,NaN
3177,시대인재부엉이라이브러리더블유(W)관독서실,서울특별시 강남구 삼성로 337,37.502124,127.059690,250,125.0,NaN
3178,시대인재부엉이라이브러리더블유(W)관4층독서실,서울특별시 강남구 삼성로 337,37.502124,127.059690,308,154.0,NaN
3179,시대인재부엉이라이브러리더블유(W)관5층독서실,서울특별시 강남구 삼성로 337,37.502124,127.059690,308,154.0,NaN
3207,시대인재3관5층학원,서울특별시 강남구 도곡로 451,37.498884,127.059753,10530,198.0,NaN
3577,시대인재2관학원,서울특별시 강남구 도곡로 510,37.498912,127.061955,10530,70.0,1.0
3649,시대인재수학스쿨센터학원,서울특별시 강남구 도곡로 450,37.498112,127.059759,10530,176.0,NaN

In [308]:
gn_all.loc[gn_all['학원명'].str.find('씨앤에이')>=0, '어린이보호구역여부']=1

In [309]:
gn_all[gn_all['학원명'].str.find('씨앤에이')>=0] #학원명 일부 변경

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
96,씨앤에이논술학원,서울특별시 강남구 도곡로 450,37.498112,127.059759,340,118.0,1.0

In [310]:
gn_all.loc[gn_all['학원명'].str.find('신어지')>=0, '어린이보호구역여부']=1

In [311]:
gn_all[gn_all['학원명'].str.find('신어지')>=0] #학원명 일부 변경

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
3563,신어지보습학원,서울특별시 강남구 남부순환로 2941,37.494227,127.061785,683,264.0,1.0

In [312]:
gn_all[gn_all['학원명'].str.find('씨앤씨미술')>=0] #학원 두개로 나뉘어짐 : 제거

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
2151,강남씨앤씨미술학원,서울특별시 강남구 선릉로 311,37.497329,127.052073,435,66.0,NaN
2915,대치씨앤씨미술학원,서울특별시 강남구 도곡로 323,37.496077,127.051344,270,53.0,NaN

In [313]:
gn_all[gn_all['학원명'].str.find('매쓰')>=0] # 없어짐

,학원명,주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
107,다원매쓰아이(Math i)학원,서울특별시 강남구 삼성로 227,37.497404,127.061241,500,150.0,NaN
158,매쓰무적학원,서울특별시 강남구 남부순환로 2912,37.490839,127.057241,91,40.0,NaN
175,펜토매쓰피엘수학학원,서울특별시 강남구 선릉로 227,37.495832,127.052729,48,68.0,NaN
203,이아이이(EIE)매쓰캔학원,서울특별시 강남구 개포로22길 94,37.475177,127.052986,40,82.0,NaN
323,도곡시매쓰보습학원,서울특별시 강남구 도곡로13길 5,37.491490,127.036439,32,42.0,NaN
360,연세매쓰클리닉(YONSEI MATH CLINIC)수학교습소,서울특별시 강남구 선릉로 664,37.515896,127.042286,16,4.0,NaN
656,매쓰피아수학교습소,서울특별시 강남구 역삼로52길 14,37.498529,127.047949,12,4.0,NaN
718,매쓰코드수학학원,서울특별시 강남구 언주로167길 35,37.526375,127.030267,40,91.0,NaN
724,매쓰몽수학학원,서울특별시 강남구 선릉로 120,37.491125,127.059896,150,110.0,NaN
743,다원매쓰아이(Math i)2관학원,서울특별시 강남구 도곡로 521,37.500032,127.063228,340,34.0,NaN
744,시매쓰영재중등관학원,서울특별시 강남구 도곡로 409,37.497382,127.055170,150,68.0,NaN
981,에이매쓰학원,서울특별시 강남구 언주로30길 10,37.487362,127.051326,12,75.0,NaN
991,하이매쓰큐학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,112,50.0,NaN
1036,하이매쓰학원,서울특별시 강남구 도곡로 409,37.497382,127.055170,346,207.0,NaN
1171,매쓰포유수학교습소,서울특별시 강남구 삼성로67길 33,37.500355,127.056910,10,5.0,NaN
1273,잉글리쉬&매쓰매니저학원,서울특별시 강남구 선릉로 642,37.513980,127.042813,252,163.0,NaN
1415,매쓰포인트수학학원,서울특별시 강남구 압구정로34길 11,37.527389,127.030957,120,142.0,NaN
1648,엑스매쓰(XMATH)학원,서울특별시 강남구 선릉로64길 7,37.497974,127.052893,60,82.0,NaN
1695,매쓰더케이(math.TheK)수학교습소,서울특별시 강남구 압구정로 224,37.528536,127.032160,12,5.0,NaN
1734,에스메타매쓰(S Meta Math)수학교습소,서울특별시 강남구 남부순환로365길 26,37.487018,127.039611,12,4.0,NaN
1736,시매쓰영재중등2관학원,서울특별시 강남구 도곡로 408,37.496688,127.055264,150,176.0,NaN
1832,닥터매쓰바른학원,서울특별시 서초구 서운로 207,37.501486,127.021698,144,77.0,NaN
1853,매쓰점프수학교습소,서울특별시 강남구 헌릉로570길 30,37.463158,127.102936,6,6.0,NaN
1873,줌매쓰1(ZOOM MATH 1)수학교습소,서울특별시 강남구 삼성로 151,37.492126,127.062565,9,3.0,NaN
1874,줌매쓰2(ZOOM MATH 2)수학교습소,서울특별시 강남구 삼성로 151,37.492126,127.062565,9,3.0,NaN
1875,줌매쓰3(ZOOM MATH 3)수학교습소,서울특별시 강남구 삼성로 151,37.492126,127.062565,9,3.0,NaN
2034,사고력수학시매쓰학원,서울특별시 강남구 도곡로 408,37.496688,127.055264,56,152.0,NaN
2296,피매쓰(P.math)수학교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,72,8.0,NaN
2363,키워드매쓰원격학원,서울특별시 강남구 자곡로 204-5,37.474278,127.105402,0,0.0,NaN
2476,매쓰탑수학학원,서울특별시 강남구 압구정로18길 5,37.524600,127.024401,15,70.0,NaN
2491,이매쓰학원,서울특별시 강남구 선릉로64길 15-7,37.498545,127.053242,50,71.0,NaN
2531,스타매쓰주니어수학교습소,서울특별시 강남구 압구정로20길 15,37.524823,127.025424,6,2.0,NaN
2754,매쓰스토리수학교습소,서울특별시 강남구 헌릉로590길 63,37.460288,127.101186,65,8.0,NaN
2788,스타매쓰학원,서울특별시 강남구 논현로175길 42,37.525013,127.025177,35,68.0,NaN
2862,미스터매쓰수학교습소,서울특별시 강남구 선릉로69길 7,37.498448,127.051206,81,8.0,NaN
2888,영매쓰수학교습소,서울특별시 강남구 학동로63길 11,37.518748,127.044780,40,5.0,NaN
2900,엠케이매쓰(MK MATH)수학교습소,서울특별시 강남구 논현로159길 17,37.522937,127.026638,5,7.0,NaN
2913,영매쓰수학학원,서울특별시 강남구 선릉로132길 39,37.518663,127.044374,110,102.0,NaN
3027,온매쓰(math)수학교습소,서울특별시 강남구 삼성로 155,37.493828,127.062941,51,5.0,NaN
3047,지니매쓰수학교습소,서울특별시 강남구 자곡로 106,37.471921,127.095003,48,9.0,NaN
3197,다원매쓰아이수학학원,서울특별시 강남구 삼성로63길 15,37.499634,127.058933,8370,180.0,NaN
3527,레드매쓰수학학원,서울특별시 강남구 도곡로 531,37.500321,127.064499,32,60.0,NaN
3593,시매쓰압구정학원,서울특별시 강남구 압구정로42길 13,37.527967,127.035537,75,151.0,NaN

In [314]:
gn_all['어린이보호구역여부'].fillna(0, inplace=True)

In [315]:
gn_all.rename(columns = {'Latitude' : '위도', 'Longitude' : '경도'}, inplace = True)

In [316]:
gn_all

,학원명,주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0,0.0
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0,0.0
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0,0.0
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0,0.0
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0,0.0
...,...,...,...,...,...,...,...
3663,김형은수학교습소,서울특별시 강남구 선릉로 227,37.495832,127.052729,4,20.0,0.0
3664,대치지아이(Daechi GI)영어교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,40,8.0,0.0
3665,소리샘피아노교습소,서울특별시 강남구 광평로10길 15,37.482024,127.082132,9,3.0,0.0
3666,예섬프론티어학원,서울특별시 강남구 도곡로 430,37.497506,127.057551,2840,278.0,0.0
3667,대찬학원,서울특별시 강남구 도곡로 432,37.497571,127.057751,28565,130.0,0.0

In [ ]:
# 노원 선정 학원 정리

In [60]:
nw_all = pd.read_csv("../기존 입지 분석 이용 데이터/노원구 학원 좌표화&인원.csv")
nw_all

,학원명,도로명주소,Latitude,Longitude,정원합계,일시수용능력인원합계
0,마들단디독서실,서울특별시 노원구 동일로227길 26,37.668783,127.053725,167,167
1,청우어학원,서울특별시 노원구 동일로 1368,37.650750,127.061939,90,147
2,경희로맨틱발레(Romanticballet)무용학원,서울특별시 노원구 동일로 1393,37.652941,127.060515,60,99
3,중계새롬보습학원,서울특별시 노원구 중계로 8길 29,37.645985,127.082640,55,105
4,한샘영재보습학원,서울특별시 노원구 섬밭로 209,37.635445,127.064244,50,85
...,...,...,...,...,...,...
1443,설명수학교습소,서울특별시 노원구 한글비석로 444,37.663673,127.068542,12,7
1444,이룸해법학원,서울특별시 노원구 중계로12가길 29,37.648332,127.082910,35,83
1445,곽쌤의꽉잡는수학학원,서울특별시 노원구 노원로1길 67,37.620810,127.083602,48,92
1446,그림아트스튜디오미술교습소,서울특별시 노원구 중계로 230,37.652831,127.075926,46,9
1447,그림드림미술교습소,서울특별시 노원구 동일로192길 77,37.628081,127.076843,16,9

In [155]:
n1 = list(academy[academy['지역구'] == '노원구'].iloc[:,2])
n1

['중계미래탐구초등연재센터학원',
 '중계덕스어학원',
 '아발론랭콘중계어학원',
 '하이레벨수학전문학원',
 '소마사고력수학학원',
 '청담어학원',
 '중계스텔라어학원',
 '국풍2000학원',
 '올림피아드영재센터학원',
 '모멘텀아스트라학원',
 '알로곤영재센터학원',
 '하이레벨수학전문학원',
 '멘처스학원',
 '중계세일입시학원',
 'CMS중계중등영재2관학원',
 '수학에미친사람들중계관학원']

In [156]:
n2 = list(nw_all[nw_all['학원명'].isin(n1)].loc[:,'학원명'])
n2

['청담어학원',
 '중계세일입시학원',
 '수학에미친사람들중계관학원',
 '아발론랭콘중계어학원',
 '하이레벨수학전문학원',
 '소마사고력수학학원',
 '알로곤영재센터학원',
 '올림피아드영재센터학원',
 '중계덕스어학원']

In [157]:
nw_missing = list(set(n1)-set(n2))
nw_missing

['중계스텔라어학원',
 '국풍2000학원',
 '중계미래탐구초등연재센터학원',
 '모멘텀아스트라학원',
 '멘처스학원',
 'CMS중계중등영재2관학원']

In [158]:
for i in nw_missing :
    try:
        print(nw_all[i[:3] == nw_all['학원명'].str[:3]])
    except:
        print(i)

               학원명              도로명주소   Latitude   Longitude  정원합계  \
673  중계스즈키바이올린첼로학원  서울특별시 노원구 중계로 225  37.649827  127.074332    80

     일시수용능력인원합계  어린이보호구역여부
673          43        0.0
              학원명               도로명주소   Latitude   Longitude  정원합계  \
723  국풍2000중계1관학원  서울특별시 노원구 중계로18길 9  37.651137  127.077782   475
909  국풍2000중계2관학원   서울특별시 노원구 중계로 202  37.650868  127.077805   475

     일시수용능력인원합계  어린이보호구역여부
723          90        0.0
909         163        0.0
                 학원명                도로명주소   Latitude   Longitude  정원합계  \
37    중계미래탐구초등영재센터학원  서울특별시 노원구 한글비석로 232  37.648377  127.076929  1100
142       중계미래탐구중등학원  서울특별시 노원구 한글비석로 232  37.648377  127.076929  1660
701      중계미래탐구영재관학원  서울특별시 노원구 한글비석로 232  37.648377  127.076929   240
1031    중계미래탐구영과센터학원  서울특별시 노원구 한글비석로 232  37.648377  127.076929   740

      일시수용능력인원합계  어린이보호구역여부
37           191        0.0
142          662        0.0
701           83        0.0
1031         109        0.0
Empty DataFrame
Columns: [학원명, 도로명주소, Latitude, Longitude, 정원합계, 일시수용능력인원합계, 어린이보호구역여부]
Index: []
Empty DataFrame
Columns: [학원명, 도로명주소, Latitude, Longitude, 정원합계, 일시수용능력인원합계, 어린이보호구역여부]
Index: []
Empty DataFrame
Columns: [학원명, 도로명주소, Latitude, Longitude, 정원합계, 일시수용능력인원합계, 어린이보호구역여부]
Index: []

In [163]:
nw_all.loc[nw_all['학원명'].str.find('국풍')>=0, '어린이보호구역여부']=1

In [164]:
nw_all[nw_all['학원명'].str.find('국풍')>=0]

,학원명,도로명주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
723,국풍2000중계1관학원,서울특별시 노원구 중계로18길 9,37.651137,127.077782,475,90,1.0
909,국풍2000중계2관학원,서울특별시 노원구 중계로 202,37.650868,127.077805,475,163,1.0
1099,국풍온원격학원,서울특별시 노원구 중계로 202,37.650868,127.077805,109989,9999,1.0

In [170]:
nw_all.loc[nw_all['학원명'].str.find('미래탐구초등영재')>=0, '어린이보호구역여부']=1

In [171]:
nw_all[nw_all['학원명'].str.find('미래탐구초등영재')>=0]

,학원명,도로명주소,Latitude,Longitude,정원합계,일시수용능력인원합계,어린이보호구역여부
37,중계미래탐구초등영재센터학원,서울특별시 노원구 한글비석로 232,37.648377,127.076929,1100,191,1.0

In [172]:
nw_all.loc[nw_all['학원명'].isin(n1),'어린이보호구역여부']=1

In [173]:
nw_all['어린이보호구역여부'].fillna(0, inplace=True)

In [196]:
nw_all.rename(columns = {'Latitude' : '위도', 'Longitude' : '경도'}, inplace = True)

In [197]:
nw_all

,학원명,도로명주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부
0,마들단디독서실,서울특별시 노원구 동일로227길 26,37.668783,127.053725,167,167,0.0
1,청우어학원,서울특별시 노원구 동일로 1368,37.650750,127.061939,90,147,0.0
2,경희로맨틱발레(Romanticballet)무용학원,서울특별시 노원구 동일로 1393,37.652941,127.060515,60,99,0.0
3,중계새롬보습학원,서울특별시 노원구 중계로 8길 29,37.645985,127.082640,55,105,0.0
4,한샘영재보습학원,서울특별시 노원구 섬밭로 209,37.635445,127.064244,50,85,0.0
...,...,...,...,...,...,...,...
1443,설명수학교습소,서울특별시 노원구 한글비석로 444,37.663673,127.068542,12,7,0.0
1444,이룸해법학원,서울특별시 노원구 중계로12가길 29,37.648332,127.082910,35,83,0.0
1445,곽쌤의꽉잡는수학학원,서울특별시 노원구 노원로1길 67,37.620810,127.083602,48,92,0.0
1446,그림아트스튜디오미술교습소,서울특별시 노원구 중계로 230,37.652831,127.075926,46,9,0.0
1447,그림드림미술교습소,서울특별시 노원구 동일로192길 77,37.628081,127.076843,16,9,0.0

## 학원 - 본인 위치 기준으로 : 근처 500m 이내(도보 8분) 학원 수, 학원 정원 합, 휴게음식점 수, 교통사고 건수, 횡단보도 개수 (top 이 후보) -> mlcp

In [48]:
# longtitude 경도 latitude 위도

In [190]:
!pip install haversine

Requirement already satisfied: haversine in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.8.0)

[notice] A new release of pip is available: 23.1.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

In [191]:
from haversine import haversine

In [193]:
<<예시 모아둔 BLOCK>>

# haversine 사용법 usage example   
kyobo = (37.504030, 127.024099) # 교보 문고 위도/경도
gangnam = (37.497175,127.027926) # 강남역 위도/경도
haversine(kyobo, gangnam) * 1000 # km to m

# tuple usage example
location1 = tuple([data.loc[0, '위도'], data.loc[0, '경도']])
location1

# 열 삭제
data.drop(labels = '학원수', axis = 1)

NameError: name 'data' is not defined

In [317]:
data = gn_all.copy()

In [319]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3668 entries, 0 to 3667
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   학원명         3668 non-null   object
 1   주소          3661 non-null   object
 2   위도          3643 non-null   float64
 3   경도          3643 non-null   float64
 4   정원합계        3668 non-null   int64
 5   일시수용능력인원합계  3666 non-null   float64
 6   어린이보호구역여부   3668 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 200.7+ KB

In [320]:
# 주소 없는 학원 제거
data.dropna(subset = ['위도'], inplace = True)

In [321]:
# 둘다 00인 학원 삭제
idx = list(data[data['일시수용능력인원합계']+data['정원합계']<=0].index)
data.drop(idx, axis=0, inplace=True)

In [322]:
# 인원 결측치 삭제

data[data['일시수용능력인원합계'].isna()]
data.dropna(subset = ['일시수용능력인원합계'], inplace = True)

In [323]:
# 일시수용 & 정원합계 비교 후 적은 값으로
data.loc[data['정원합계'] >= data['일시수용능력인원합계'], '인원'] = data['일시수용능력인원합계']
data.loc[data['정원합계'] < data['일시수용능력인원합계'], '인원'] = data['정원합계']

In [327]:
data = data.reset_index(drop=True)

In [328]:
data

,학원명,주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부,인원
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0,0.0,10.0
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0,0.0,1655.0
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0,0.0,80.0
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0,0.0,61.0
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0,0.0,4.0
...,...,...,...,...,...,...,...,...
3611,김형은수학교습소,서울특별시 강남구 선릉로 227,37.495832,127.052729,4,20.0,0.0,4.0
3612,대치지아이(Daechi GI)영어교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,40,8.0,0.0,8.0
3613,소리샘피아노교습소,서울특별시 강남구 광평로10길 15,37.482024,127.082132,9,3.0,0.0,3.0
3614,예섬프론티어학원,서울특별시 강남구 도곡로 430,37.497506,127.057551,2840,278.0,0.0,278.0
3615,대찬학원,서울특별시 강남구 도곡로 432,37.497571,127.057751,28565,130.0,0.0,130.0

In [337]:
# 해당 학원 기준 반경 500m 학원 수 총합 counting
for i in range(len(data)) :
    cnt = 0
    location1 = tuple([data.loc[i, '위도'], data.loc[i, '경도']])
    for j in range(len(data)):
        if i==j:
            continue
        else:
            location2 = tuple([data.loc[j, '위도'], data.loc[j, '경도']])
            if haversine(location1, location2)*1000<=500 :
                cnt += 1
    data.loc[i, '근처학원수'] = cnt-1

In [338]:
# 해당 학원 기준 반경 500m 학원수강생 총합 counting

for i in range(len(data)) :
    s = 0
    location1 = tuple([data.loc[i, '위도'], data.loc[i, '경도']])
    for j in range(len(data)):
        if i==j:
            continue
        else:
            location2 = tuple([data.loc[j, '위도'], data.loc[j, '경도']])
            if haversine(location1, location2)*1000<=500 :             
                s += data.loc[j, '인원']
    data.loc[i, '근처수강생총합'] = s

In [339]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3616 entries, 0 to 3615
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   학원명         3616 non-null   object
 1   주소          3616 non-null   object
 2   위도          3616 non-null   float64
 3   경도          3616 non-null   float64
 4   정원합계        3616 non-null   int64
 5   일시수용능력인원합계  3616 non-null   float64
 6   어린이보호구역여부   3616 non-null   float64
 7   인원          3616 non-null   float64
 8   근처학원수       3616 non-null   float64
 9   근처수강생총합     3616 non-null   float64
 10  근처휴게음식점수    3616 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 310.9+ KB

In [340]:
store = pd.read_csv("../기존 입지 분석 이용 데이터/강남구 휴게음식점 좌표.csv", encoding = "cp949", index_col=0)
store

,영업상태명,도로명주소,업태구분명,위도,경도
0,영업/정상,서울특별시 강남구 도곡로 532,편의점,37.499780,127.064569
1,영업/정상,서울특별시 강남구 강남대로66길 16,편의점,37.491901,127.032161
2,영업/정상,서울특별시 강남구 영동대로 511,패스트푸드,37.510398,127.061193
3,영업/정상,서울특별시 강남구 개포로 512,편의점,37.489271,127.068818
4,영업/정상,서울특별시 강남구 삼성로 151,편의점,37.492126,127.062565
...,...,...,...,...,...
2322,영업/정상,"서울특별시 강남구 밤고개로 165, 근린생활시설동 지상1층 101,102호 (자곡동...",편의점,37.478265,127.104967
2323,영업/정상,"서울특별시 강남구 도산대로 443, 청담빌딩 지상1층 (청담동)",커피숍,37.524222,127.044442
2324,영업/정상,"서울특별시 강남구 남부순환로 3104, SETEC 지상1층 (대치동)",패스트푸드,37.495712,127.071796
2325,영업/정상,"서울특별시 강남구 영동대로 513, 코엑스 1층 B홀 (삼성동)",커피숍,37.511683,127.059151
2326,영업/정상,"서울특별시 강남구 영동대로 513, 코엑스 1층 A홀 (삼성동)",커피숍,37.511683,127.059151

In [334]:
# 근처 상점 counting (유동인구)
for i in range(len(data)) :
    s = 0
    location1 = tuple([data.loc[i, '위도'], data.loc[i, '경도']])
    for j in range(len(store)):
        location2 = tuple([store.loc[j, '위도'], store.loc[j, '경도']])
        if haversine(location1, location2)*1000<=500 :
            s += 1
    data.loc[i, '근처휴게음식점수'] = s

In [341]:
# 근처 횡단보도 counting
crosswalk = pd.read_csv("../기존 입지 분석 이용 데이터/강남구 횡단보도 좌표.csv", encoding = "cp949", index_col=0)

In [342]:
for i in range(len(data)) :
    s = 0
    location1 = tuple([data.loc[i, '위도'], data.loc[i, '경도']])
    for j in range(len(crosswalk)):
        location2 = tuple([crosswalk.loc[j, '위도'], crosswalk.loc[j, '경도']])
        if haversine(location1, location2)*1000<=500 :
            s += 1
    data.loc[i, '근처횡단보도수'] = s

In [346]:
# 근처 사고 counting
accident = pd.read_csv("../기존 입지 분석 이용 데이터/강남구 2012_2019_교통사망사고.csv", encoding = "cp949")
accident

     지역구   발생년 주야 요일  사망자수  사상자수  중상자수  경상자수  부상신고자수          경도         위도
0    강남구  2012  야  일     1     1     0     0       0  127.050853  37.500513
1    강남구  2012  주  금     1     1     0     0       0  127.033088  37.486392
2    강남구  2012  주  월     1     1     0     0       0  127.065220  37.504596
3    강남구  2012  주  토     1     1     0     0       0  127.067447  37.500918
4    강남구  2012  야  화     1     4     2     0       1  127.065148  37.505236
..   ...   ... .. ..   ...   ...   ...   ...     ...         ...        ...
151  강남구  2019  야  목     1     0     0     0       0  127.046130  37.495727
152  강남구  2019  주  월     1     0     0     0       0  127.075418  37.497936
153  강남구  2019  야  금     1     1     1     0       0  127.079155  37.499130
154  강남구  2019  야  목     1     1     0     1       0  127.042904  37.502221
155  강남구  2019  야  화     1     0     0     0       0  127.097769  37.485819

[156 rows x 11 columns]

In [351]:
# 근처 사고 counting
for i in range(len(data)) :
    s = 0
    location1 = tuple([data.loc[i, '위도'], data.loc[i, '경도']])
    for j in range(len(accident)):
        location2 = tuple([accident.loc[j, '위도'], accident.loc[j, '경도']])
        if haversine(location1, location2)*1000<=500 :
            s = s + sum(accident.loc[j, ['사망자수','중상자수','경상자수','부상신고자수']])
    data.loc[i, '사고건수'] = s

In [352]:
data

,학원명,주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부,인원,근처학원수,근처수강생총합,근처휴게음식점수,근처횡단보도수,사고건수
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0,0.0,10.0,641.0,37069.0,99.0,59.0,2.0
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0,0.0,1655.0,142.0,17840.0,134.0,30.0,7.0
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0,0.0,80.0,443.0,40971.0,64.0,71.0,11.0
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0,0.0,61.0,190.0,13269.0,89.0,34.0,4.0
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0,0.0,4.0,42.0,1203.0,40.0,58.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3611,김형은수학교습소,서울특별시 강남구 선릉로 227,37.495832,127.052729,4,20.0,0.0,4.0,433.0,25744.0,58.0,36.0,1.0
3612,대치지아이(Daechi GI)영어교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,40,8.0,0.0,8.0,443.0,41043.0,64.0,71.0,11.0
3613,소리샘피아노교습소,서울특별시 강남구 광평로10길 15,37.482024,127.082132,9,3.0,0.0,3.0,52.0,1200.0,12.0,44.0,0.0
3614,예섬프론티어학원,서울특별시 강남구 도곡로 430,37.497506,127.057551,2840,278.0,0.0,278.0,869.0,64248.0,106.0,52.0,1.0
3615,대찬학원,서울특별시 강남구 도곡로 432,37.497571,127.057751,28565,130.0,0.0,130.0,832.0,63575.0,99.0,52.0,1.0

In [353]:
gn_all = data.copy()
gn_all

,학원명,주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부,인원,근처학원수,근처수강생총합,근처휴게음식점수,근처횡단보도수,사고건수
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0,0.0,10.0,641.0,37069.0,99.0,59.0,2.0
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0,0.0,1655.0,142.0,17840.0,134.0,30.0,7.0
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0,0.0,80.0,443.0,40971.0,64.0,71.0,11.0
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0,0.0,61.0,190.0,13269.0,89.0,34.0,4.0
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0,0.0,4.0,42.0,1203.0,40.0,58.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3611,김형은수학교습소,서울특별시 강남구 선릉로 227,37.495832,127.052729,4,20.0,0.0,4.0,433.0,25744.0,58.0,36.0,1.0
3612,대치지아이(Daechi GI)영어교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,40,8.0,0.0,8.0,443.0,41043.0,64.0,71.0,11.0
3613,소리샘피아노교습소,서울특별시 강남구 광평로10길 15,37.482024,127.082132,9,3.0,0.0,3.0,52.0,1200.0,12.0,44.0,0.0
3614,예섬프론티어학원,서울특별시 강남구 도곡로 430,37.497506,127.057551,2840,278.0,0.0,278.0,869.0,64248.0,106.0,52.0,1.0
3615,대찬학원,서울특별시 강남구 도곡로 432,37.497571,127.057751,28565,130.0,0.0,130.0,832.0,63575.0,99.0,52.0,1.0

In [354]:
gn_all.to_csv('강남구데이터프레임.csv',index=False)