In [9]:
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

In [3]:
import pandas as pd
import numpy as np

In [19]:
gn = pd.read_csv("강남구데이터프레임.csv")
gn

,학원명,주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부,인원,근처학원수,근처수강생총합,근처휴게음식점수,근처횡단보도수,사고건수
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0,0.0,10.0,641.0,37069.0,99.0,59.0,2.0
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0,0.0,1655.0,142.0,17840.0,134.0,30.0,7.0
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0,0.0,80.0,443.0,40971.0,64.0,71.0,11.0
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0,0.0,61.0,190.0,13269.0,89.0,34.0,4.0
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0,0.0,4.0,42.0,1203.0,40.0,58.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3611,김형은수학교습소,서울특별시 강남구 선릉로 227,37.495832,127.052729,4,20.0,0.0,4.0,433.0,25744.0,58.0,36.0,1.0
3612,대치지아이(Daechi GI)영어교습소,서울특별시 강남구 삼성로 212,37.497418,127.065327,40,8.0,0.0,8.0,443.0,41043.0,64.0,71.0,11.0
3613,소리샘피아노교습소,서울특별시 강남구 광평로10길 15,37.482024,127.082132,9,3.0,0.0,3.0,52.0,1200.0,12.0,44.0,0.0
3614,예섬프론티어학원,서울특별시 강남구 도곡로 430,37.497506,127.057551,2840,278.0,0.0,278.0,869.0,64248.0,106.0,52.0,1.0
3615,대찬학원,서울특별시 강남구 도곡로 432,37.497571,127.057751,28565,130.0,0.0,130.0,832.0,63575.0,99.0,52.0,1.0

In [12]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [21]:
hm = gn.iloc[:, 4:]
hm

,정원합계,일시수용능력인원합계,어린이보호구역여부,인원,근처학원수,근처수강생총합,근처휴게음식점수,근처횡단보도수,사고건수
0,10,80.0,0.0,10.0,641.0,37069.0,99.0,59.0,2.0
1,11056,1655.0,0.0,1655.0,142.0,17840.0,134.0,30.0,7.0
2,160,80.0,0.0,80.0,443.0,40971.0,64.0,71.0,11.0
3,115,61.0,0.0,61.0,190.0,13269.0,89.0,34.0,4.0
4,28,4.0,0.0,4.0,42.0,1203.0,40.0,58.0,11.0
...,...,...,...,...,...,...,...,...,...
3611,4,20.0,0.0,4.0,433.0,25744.0,58.0,36.0,1.0
3612,40,8.0,0.0,8.0,443.0,41043.0,64.0,71.0,11.0
3613,9,3.0,0.0,3.0,52.0,1200.0,12.0,44.0,0.0
3614,2840,278.0,0.0,278.0,869.0,64248.0,106.0,52.0,1.0
3615,28565,130.0,0.0,130.0,832.0,63575.0,99.0,52.0,1.0

In [6]:
nw = pd.read_csv("노원구데이터프레임.csv")
nw

,학원명,도로명주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부,인원,근처학원수,근처수강생총합,근처휴게음식점수,근처횡단보도수,사고건수
0,마들단디독서실,서울특별시 노원구 동일로227길 26,37.668783,127.053725,167,167,0.0,167.0,65.0,3132.0,24.0,35.0,5.0
1,청우어학원,서울특별시 노원구 동일로 1368,37.650750,127.061939,90,147,0.0,90.0,94.0,8824.0,70.0,40.0,5.0
2,경희로맨틱발레(Romanticballet)무용학원,서울특별시 노원구 동일로 1393,37.652941,127.060515,60,99,0.0,60.0,94.0,10192.0,88.0,69.0,4.0
3,중계새롬보습학원,서울특별시 노원구 중계로 8길 29,37.645985,127.082640,55,105,0.0,55.0,51.0,2339.0,19.0,23.0,0.0
4,한샘영재보습학원,서울특별시 노원구 섬밭로 209,37.635445,127.064244,50,85,0.0,50.0,46.0,2667.0,28.0,64.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,설명수학교습소,서울특별시 노원구 한글비석로 444,37.663673,127.068542,12,7,0.0,7.0,85.0,3091.0,56.0,48.0,3.0
1444,이룸해법학원,서울특별시 노원구 중계로12가길 29,37.648332,127.082910,35,83,0.0,35.0,72.0,2988.0,29.0,30.0,0.0
1445,곽쌤의꽉잡는수학학원,서울특별시 노원구 노원로1길 67,37.620810,127.083602,48,92,0.0,48.0,61.0,1994.0,38.0,50.0,13.0
1446,그림아트스튜디오미술교습소,서울특별시 노원구 중계로 230,37.652831,127.075926,46,9,0.0,9.0,408.0,56424.0,52.0,67.0,4.0
1447,그림드림미술교습소,서울특별시 노원구 동일로192길 77,37.628081,127.076843,16,9,0.0,9.0,31.0,1852.0,58.0,52.0,5.0

In [8]:
data = pd.concat([gn, nw], ignore_index = True)
data

,학원명,주소,위도,경도,정원합계,일시수용능력인원합계,어린이보호구역여부,인원,근처학원수,근처수강생총합,근처휴게음식점수,근처횡단보도수,사고건수,도로명주소
0,예림서예학원,서울특별시 강남구 선릉로 328,37.499060,127.051930,10,80.0,0.0,10.0,641.0,37069.0,99.0,59.0,2.0,NaN
1,와이비엠어학원,서울특별시 강남구 강남대로 408,37.499223,127.027575,11056,1655.0,0.0,1655.0,142.0,17840.0,134.0,30.0,7.0,NaN
2,신세계음악학원,서울특별시 강남구 삼성로 212,37.497418,127.065327,160,80.0,0.0,80.0,443.0,40971.0,64.0,71.0,11.0,NaN
3,압구정뮤직아카데미학원,서울특별시 강남구 언주로172길 12,37.527635,127.034670,115,61.0,0.0,61.0,190.0,13269.0,89.0,34.0,4.0,NaN
4,심포니음악학원,서울특별시 강남구 학동로 513,37.519917,127.053868,28,4.0,0.0,4.0,42.0,1203.0,40.0,58.0,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5059,설명수학교습소,NaN,37.663673,127.068542,12,7.0,0.0,7.0,85.0,3091.0,56.0,48.0,3.0,서울특별시 노원구 한글비석로 444
5060,이룸해법학원,NaN,37.648332,127.082910,35,83.0,0.0,35.0,72.0,2988.0,29.0,30.0,0.0,서울특별시 노원구 중계로12가길 29
5061,곽쌤의꽉잡는수학학원,NaN,37.620810,127.083602,48,92.0,0.0,48.0,61.0,1994.0,38.0,50.0,13.0,서울특별시 노원구 노원로1길 67
5062,그림아트스튜디오미술교습소,NaN,37.652831,127.075926,46,9.0,0.0,9.0,408.0,56424.0,52.0,67.0,4.0,서울특별시 노원구 중계로 230
5063,그림드림미술교습소,NaN,37.628081,127.076843,16,9.0,0.0,9.0,31.0,1852.0,58.0,52.0,5.0,서울특별시 노원구 동일로192길 77

In [23]:
feature = ['인원','근처학원수','근처수강생총합','근처휴게음식점수','근처횡단보도수','사고건수']
target = "어린이보호구역여부"

In [26]:
X_train = data[feature]
y_train = data[target]

In [40]:
X_train

          인원  근처학원수  근처수강생총합  근처휴게음식점수  근처횡단보도수  사고건수
0       10.0  641.0  37069.0      99.0     59.0   2.0
1     1655.0  142.0  17840.0     134.0     30.0   7.0
2       80.0  443.0  40971.0      64.0     71.0  11.0
3       61.0  190.0  13269.0      89.0     34.0   4.0
4        4.0   42.0   1203.0      40.0     58.0  11.0
...      ...    ...      ...       ...      ...   ...
5059     7.0   85.0   3091.0      56.0     48.0   3.0
5060    35.0   72.0   2988.0      29.0     30.0   0.0
5061    48.0   61.0   1994.0      38.0     50.0  13.0
5062     9.0  408.0  56424.0      52.0     67.0   4.0
5063     9.0   31.0   1852.0      58.0     52.0   5.0

[5064 rows x 6 columns]

In [35]:
from sklearn.preprocessing import StandardScaler

# 스케일러 생성
scaler = StandardScaler()

# 스케일 조정
X_train_sclaed = scaler.fit_transform(X_train)

In [38]:
from sklearn.linear_model import LogisticRegression

# 모델 생성 및 학습 시키기
logistic = LogisticRegression(max_iter = 5000)
logistic.fit(X_train_sclaed, y_train)

# 결과 확인
# print("validation 데이터셋 정확도")
# logistic.score(X_train, y_val)

LogisticRegression(max_iter=5000)

In [39]:
logistic.coef_

array([[ 0.12583617, -0.05977345,  1.30682357, -0.58383945,  0.17626807,
        -1.26405709]])

In [43]:
print("validation 데이터셋 정확도")
logistic.score(X_train_sclaed, y_train)

validation 데이터셋 정확도

0.9954581358609794